### ISSUE TITLE
DefaultTextStyle is not applied

### ISSUE THREAD

**Issue by ymoussaba** [watery-desert/sliding_clipped_nav_bar#6]
```dart
DefaultTextStyle(
    style: TextStyle(),
    child: SlidingClippedNavBar(),
)
```

**Comment by watery-desert** [comment]
Provide code to produce the issue and attach screenshots/recordings to show the issue.

**Comment by ymoussaba** [comment]
Basically it is enough to follow the example provided in the README to realize it. Afterwards, when you search in the repo, you will notice that DefaultTextStyle is not used in the code.

**Comment by watery-desert** [comment]
thanks for the PR I didn't know this issue. 
BTW don't you think `.merge(DefaultTextStyle.of(context).style)` should be added here instead? Because there are `getTextStyle()` in two places. https://github.com/watery-desert/sliding_clipped_nav_bar/blob/11013e2dfe15b23da09beaa7c0238289dbbfb97d/lib/src/widget/nav_bar_button.dart#L91

**Comment by ymoussaba** [comment]
You're welcome. I tried it here before, but it messed the textHeight. It might be necessary to do more tests I guess.

**Comment by watery-desert** [comment]
I see. I will check it later if I get time 🙂 Good luck mate 👍
